spring:
  application:
    name: CONFIG
  cloud:
    config:
      server:
        git:
          basedir: /Users/liuhui/work/code/config/basedir
          uri:
          username: lh7149902@126.com
          password: Qqqqqqq1
